*** empty log message ***

diff --git a/game/Archive b/game/Archive
--- a/game/Archive
+++ b/game/Archive
@@ -26,21 +26,11 @@ fi
 #
 #	Make a flatfile.
 #
-if [ -r $DATA/$NEW_DB ]; then
-    $BIN/dbconvert $DATA/$GDBM_DB x < $DATA/$NEW_DB > $FLATFILE
+if [ -r $DATA/$GDBM_DB ]; then
+    $BIN/dbconvert $DATA/$GDBM_DB x > $FLATFILE
 else
-    if [ -r $DATA/$INPUT_DB ]; then
-        echo "No recent checkpoint db. Using older db."
-        $BIN/dbconvert $DATA/$GDBM_DB x < $DATA/$INPUT_DB > $FLATFILE
-    else
-        if [ -r $DATA/$SAVE_DB ]; then
-            echo "No input db. Using backup db."
-            $BIN/dbconvert $DATA/$GDBM_DB x < $DATA/$SAVE_DB > $FLATFILE
-        else
-            echo "No dbs. Backup attempt failed."
-	    exit 1
-        fi
-    fi
+    echo "No db. Backup attempt failed."
+    exit 1
 fi
 #
 #	Gather and archive.
