added test for BSD-style netmush.core

diff --git a/game/ReportCrash b/game/ReportCrash
--- a/game/ReportCrash
+++ b/game/ReportCrash
@@ -8,9 +8,13 @@ bug_address="tinymush-bugs@godlike.com"
 
 # Check to make sure we have a core file.
 
-if [ ! -s core ]; then
-    echo "Error. No non-zero-size core file found."
-    exit 1
+core="core"
+if [ ! -s "$core" ]; then
+    core="netmush.core"
+    if [ ! -s "$core" ]; then
+	echo "Error. No non-zero-size core file found."
+	exit 1
+    fi
 fi
 
 # Check to make sure that we can run gdb.
@@ -38,7 +42,7 @@ echo "Determining number of stack frames (ignore non-fatal errors)..."
 
 echo "where" > gdb_script.$$
 echo "quit" >> gdb_script.$$
-num_frames=`$gdb_path --nx --command=gdb_script.$$ $BIN/netmush core | \
+num_frames=`$gdb_path --nx --command=gdb_script.$$ $BIN/netmush $core | \
     tail -1 | cut -f1 -d" " | cut -f2 -d"#"`
 
 # Frames are numbered 0 through N - 1.
@@ -77,7 +81,7 @@ echo "quit" >> gdb_script.$$
 echo
 echo "Dumping the contents of $total_frames stack frames..."
 
-$gdb_path --nx --command=gdb_script.$$ $BIN/netmush core > gdb_output.$$
+$gdb_path --nx --command=gdb_script.$$ $BIN/netmush $core > gdb_output.$$
 
 rm -f gdb_script.$$
 
