fix backups-to-/ bug

diff --git a/game/Startmush b/game/Startmush
--- a/game/Startmush
+++ b/game/Startmush
@@ -6,7 +6,26 @@ PATH=/usr/ucb:/bin:/usr/bin:.; export PATH
 #
 . mush.config
 #
-#	Make sure there isn't aready a MUSH running.
+#	Make sure mush.config paths are valid.
+#
+if [ -z "$BIN" -o ! -d "$BIN" -o ! -r "$BIN" ]; then
+	echo "Invalid BIN directory in mush.config"
+	exit 1
+fi
+if [ -z "$TEXT" -o ! -d "$TEXT" -o ! -w "$TEXT" ]; then
+	echo "Invalid TEXT directory in mush.config"
+	exit 1
+fi
+if [ -z "$DATA" -o ! -d "$DATA" -o ! -w "$DATA" ]; then
+	echo "Invalid DATA directory in mush.config"
+	exit 1
+fi
+if [ -z "$BACKUP_DIR" -o ! -d "$BACKUP_DIR" -o ! -w "$BACKUP_DIR" ]; then
+	echo "Invalid BACKUP_DIR in mush.config; using ."
+	BACKUP_DIR=.
+fi
+#
+#	Make sure there isn't already a MUSH running.
 #
 if [ -r mush.pid ]; then
 	oldpid=`cat mush.pid`
@@ -45,11 +64,7 @@ if [ -r $DATA/$INPUT_DB.KILLED ]; then
 	DBDATE=`date +%m%d-%H%M`
 	end="`tail -1 $DATA/$INPUT_DB.KILLED`"
 	if [ "$end" = "***END OF DUMP***" ]; then
-		if [ -d $BACKUP_DIR ]; then
-			NEWFILE=$BACKUP_DIR/$GAMENAME.$DBDATE
-		else
-			NEWFILE=$GAMENAME.$DBDATE
-		fi
+		NEWFILE=$BACKUP_DIR/$GAMENAME.$DBDATE
 		mv $DATA/$INPUT_DB.KILLED $NEWFILE
 		echo "A non-corrupt $INPUT_DB.KILLED file was present."
 		echo "This means that a flatfile was successfully saved after the reception"
@@ -59,11 +74,7 @@ if [ -r $DATA/$INPUT_DB.KILLED ]; then
 		echo "If this restoration is successful, you can then type ./Startmush again."
 		exit 1
 	else
-		if [ -d $BACKUP_DIR ]; then
-			NEWFILE=$BACKUP_DIR/$GAMENAME.$DBDATE.CORRUPT
-		else
-			NEWFILE=$GAMENAME.$DBDATE.CORRUPT
-		fi
+		NEWFILE=$BACKUP_DIR/$GAMENAME.$DBDATE.CORRUPT
 		mv $DATA/$INPUT_DB.KILLED $NEWFILE
 		echo "A corrupt $INPUT_DB.KILLED file was present."
 		echo "This means that there was an unsuccessful attempt to save a flatfile"
@@ -99,11 +110,7 @@ if [ -r $DATA/$CRASH_DB ]; then
 		exit 1
 	else
 		DBDATE=`date +%m%d-%H%M`
-		if [ -d $BACKUP_DIR ]; then
-			NEWFILE=$BACKUP_DIR/$GAMENAME.$DBDATE.CORRUPT
-		else
-			NEWFILE=$GAMENAME.$DBDATE.CORRUPT
-		fi
+		NEWFILE=$BACKUP_DIR/$GAMENAME.$DBDATE.CORRUPT
 		mv -f $DATA/$CRASH_DB $NEWFILE 
 		echo "A corrupt $CRASH_DB file is present."
 		echo "This indicates an unsuccessful flatfile save during a panic-restart."
